Fix compilation error
libraries/Bounce2/src/Bounce2.h:209:10: error: extra qualification 'Bounce::' on member 'changed' [-fpermissive]
  209 |     bool Bounce::changed( ) { return getStateFlag(CHANGED_STATE); }
      |          ^~~~~~

Regression introduced in 01e6fc9398d3a59544c20d6d8000117d6dcd0246

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>